### PR TITLE
Add Venus Lumanglas details

### PR DESCRIPTION
**Pull request by binos30**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has a conflict, please rebase.

**Comment by Jansalvador1445** [comment]
Still has `conflicts`, please rebase, don't to forget to pull the lastest on the master.

**Comment by Jansalvador1445** [comment]
This is now good but can you add `username` on your data? In that way, we would not file another ticket and other PR for that :D

**Comment by Jansalvador1445** [comment]
e.g. `"username" : "juan_delazcruz_123"`

**Comment by Jansalvador1445** [comment]
This is good, can you comment on the issue here? Thansk

**Comment by binos30** [comment]
> This is good, can you comment on the issue here? Thansk

#184

**Comment by Jansalvador1445** [comment]
Merging this now and adding you as Contributor.

@all-contributor please add @binos30 for content

**Comment by Jansalvador1445** [comment]
@all-contributors please add @binos30 for content

**Pull request merged**
