### PR TITLE
Add Katherine Mariñas to Dev Board

### PR DESCRIPTION
**Pull request by Kathorsiii**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Hi @Kathorsiii ! Has a conflict, can you rebase it? thanks!

**Comment by Jansalvador1445** [comment]
@all-contributors please add @Kathorsiii for content

**Comment by Kathorsiii** [comment]
> Hi @Kathorsiii ! Has a conflict, can you rebase it? thanks!

Sir if nakapag-rebase na, do I need to create a new pull request?

**Comment by Jansalvador1445** [comment]
Hello @Kathorsiii ! No need Kath, `push` will do.

**Comment by Kathorsiii** [comment]
> Hello @Kathorsiii ! No need Kath, `push` will do.

H Sir! Nag-push na po ako sir.

**Comment by Jansalvador1445** [comment]
Hello @Kathorsiii ! Still has `conflict` it maybe, try to close this Pr then recreate one, mejo outdated na yung repo nung napag rebase.

`git checkout master`
git pull
git checkout -b branch_name
// add codes
git add .
git commit -m "add messages here"
git push

**Comment by Jansalvador1445** [comment]
Don't forget to add the new data which is the 'username'.

'"username" : "your_github_username"'

**Comment by Jansalvador1445** [comment]
@all-contributors please add @Kathorsiii  for content

Congratulations Katherine! Wohooo! Keep it up! :D

**Pull request closed without merging**
