### PR TITLE
Added PR template

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolve issue #42 .

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Good Job, @96RadhikaJadhav ! Keep it up! ;) 

Closes #42 !! 

call @all-contributors ! :D

**Comment by Jansalvador1445** [comment]
call @all-contributors @96RadhikaJadhav

**Comment by Jansalvador1445** [comment]
@all-contributors add @96RadhikaJadhav  for content

**Comment by joshuadeguzman** [comment]
@all-contributors add @96RadhikaJadhav for doc

**Pull request merged**
