### PR TITLE
Add kevin-tuazon details

### PR DESCRIPTION
**Pull request by kvntzn**
add kevin tuazon details in devs.json

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has a `Conflict`. please rebase. Thank you!

**Comment by Jansalvador1445** [comment]
This is good but did you already create an issue for this? if Yes please comment down below! Thanks! :D

**Comment by kvntzn** [comment]
#199

**Comment by Jansalvador1445** [comment]
Nice! Congratulations! Merging this now, closing #199, and then add you as a contributor! Keep it up! :D

@all-contributors please add @kvntzn for content

**Comment by Jansalvador1445** [comment]
@all-contributors please add @kvntzn for content

**Pull request merged**
