### PR TITLE
Add Sherwyne devs.json

### PR DESCRIPTION
**Pull request by Sherwyne**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has a conflict, please rebase.

**Comment by Jansalvador1445** [comment]
Kinldy select the PR. I think it is duplicated. Thanks

**Comment by Sherwyne** [comment]
Done rebase

**Comment by Jansalvador1445** [comment]
Codes are all goods ready for merge but one question did you filed an issue for this one? if yes kindly, drop it here! Thanks!

**Comment by Sherwyne** [comment]
Great! thanks, here's the filled issue.
https://github.com/flutterph/devs/issues/100

**Comment by Jansalvador1445** [comment]
Merging this one! Congrats! :D

Closes #100 , Adding you also to the contributor board. @all-contributors please add @Sherwyne for content

**Pull request merged**
