### PR TITLE
Add "Arlovzki" details, also add .vscode for gitignore.

### PR DESCRIPTION
**Pull request by Arlovzki**
I added .vscode on gitignore because I am using fvm ( Flutter Version Management).

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has `conflict` can you rebase it.

**Comment by ram231** [comment]
Hi @Arlovzki `.vscode` has already been added to `.gitignore` see line 11. Thanks!

**Comment by ram231** [comment]
Hi @Arlovzki. Can you rebase it?

**Comment by ram231** [comment]
Thanks! Merging it now.

**Pull request merged**
