### PR TITLE
Add Eruel Ursua details

### PR DESCRIPTION
**Pull request by EruelUrsua**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
This is Good for merge but just a single question,  did you filed an issue for this? if yes kindly comment here! Thanks!

**Comment by EruelUrsua** [comment]
yes just forgot to comment close 135 sorry

**Comment by Jansalvador1445** [comment]
Closes #135 , Merging this, and then adding you as contributor @all-contributor please add @EruelUrsua for content! 

Congrats bro! Keep it up! :D

**Comment by Jansalvador1445** [comment]
@all-contributor please add @EruelUrsua for content

**Comment by Jansalvador1445** [comment]
@all-contributors please add @EruelUrsua  for content

**Pull request merged**
