### PR TITLE
Add Khalid Usman details

### PR DESCRIPTION
**Pull request by kusman28**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has a conflict, please rebase. Thanks!

**Comment by kusman28** [comment]
> Has a conflict, please rebase. Thanks!

Hi Sir, can you check it again? :)

**Comment by Jansalvador1445** [comment]
This is Good! Question, already filed an issue for this? if Yes, kindly comment below. Thanks! :D

**Comment by kusman28** [comment]
Yes Sir :)

**Comment by Jansalvador1445** [comment]
Kindly, comment it here. thanks!

**Comment by kusman28** [comment]
> Kindly, comment it here. thanks!

#153

**Comment by Jansalvador1445** [comment]
All goods, mergin this one and closes #153  and adding you as contributor.

@all-contributors please add @kusman28 for content

**Pull request merged**
