### PR TITLE
Add Kim Arthur Lorenzo  details

### PR DESCRIPTION
**Pull request by artdev-hash**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
This is 'Approved' on my side.

**Comment by Jansalvador1445** [comment]
Has a `conflict` can you `rebase` the project? Thanks! If there's an issue/having trouble. Don't hesitate to ping us! :D

**Comment by artdev-hash** [comment]
sir done rebasing ok na po ba? thank you po...

**Comment by Jansalvador1445** [comment]
Hello @artdev-hash! Still having a conflict with this.
Screen Shot 2021-02-08 at 9 29 25 AM

**Comment by Jansalvador1445** [comment]
Conflict, please rebase this to the master branch

**Pull request closed without merging**
