### PR TITLE
[docs] add template for feature request | closes #44

### LINKED ISSUE #44: [docs] Add template for feature request

### PR DESCRIPTION
**Pull request by nixdorgu**
Closes #44

### CODE REVIEW

**Review by joshuadeguzman — CHANGES_REQUESTED** [review]
Hello @nixdorgu,

Thank you for looking into this.

Although I haven't much details about the ticket, you can take a look at the following article to help you with the templates:

Article:
https://dev.to/dailydotdev/making-most-out-of-github-templates-46n7

Let me know if you need any further help!

**Comment by nixdorgu** [comment]
> Hello @nixdorgu,
> 
> Thank you for looking into this.
> 
> Although I haven't much details about the ticket, you can take a look at the following article to help you with the templates:
> 
> Article:
> https://dev.to/dailydotdev/making-most-out-of-github-templates-46n7
> 
> Let me know if you need any further help!

Hi Sir @joshuadeguzman , am currently looking into this! Thank you so much for the resource

**Review by joshuadeguzman — APPROVED** [review]

**Comment by joshuadeguzman** [comment]
This looks great! @nixdorgu  🎉

**Comment by joshuadeguzman** [comment]
@all-contributors add @nixdorgu  for docs

**Comment by nixdorgu** [comment]
> This looks great! @nixdorgu 🎉

Thank you so much Sir @joshuadeguzman and thank you once again for the resource - it was a big help!

**Pull request merged**
