### PR TITLE
Added Rian Barriga

### PR DESCRIPTION
**Pull request by CodePhilanthropist**
Close ticket #149 @joshuadeguzman

### CODE REVIEW

**Comment by CodePhilanthropist** [comment]
Hello @joshuadeguzman kindly review my pr

**Comment by Jansalvador1445** [comment]
Has a conflict, please rebase.

**Comment by CodePhilanthropist** [comment]
Updated. Request for review.

**Comment by Jansalvador1445** [comment]
Still has a conflict, please rebase again.

**Comment by Jansalvador1445** [comment]
Duplicate issue, closing this one

**Pull request closed without merging**
