### PR TITLE
Add Bern details

### PR DESCRIPTION
**Pull request by lesteroyal**

### CODE REVIEW

**Comment by lesteroyal** [comment]
Sir, I've created again a pull request. I rebase the branch.

**Comment by Jansalvador1445** [comment]
This is good, kindly comment down the filed issue. Thanks, @lesteroyal !

**Comment by lesteroyal** [comment]
Issue: Add details #111
Thanks sir @Jansalvador1445 !

**Comment by Jansalvador1445** [comment]
Nice! Thank you sir @lesteroyal ! Merging this now, adding you as @all-contributors please add @lesteroyal  for content! 

Congrats @lesteroyal ! Keep it up! :D

**Pull request merged**
