### PR TITLE
Add Oliver Rhyme G. Añasco details

### PR DESCRIPTION
**Pull request by OliverRhyme**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has a conflict, Please rebase, Thanks!

**Comment by OliverRhyme** [comment]
Done rebasing thanks!

**Comment by OliverRhyme** [comment]
> Has a conflict, Please rebase, Thanks!

Done rebasing thanks!

**Comment by Jansalvador1445** [comment]
Merging this now, Congrats! Adding you ad Contributor! :D

@all-contributors please add @OliverRhyme for content

**Comment by OliverRhyme** [comment]
Closes #284

**Pull request merged**
