### PR TITLE
Add royce chua details

### PR DESCRIPTION
**Pull request by roycechua23**
Added my details to the devs.json

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
This is Good! Did you filed an issue here? if yes please comment down! :D

**Comment by roycechua23** [comment]
Yes sir @Jansalvador1445  I filed my issue here #209 [https://github.com/flutterph/devs/issues/209](https://github.com/flutterph/devs/issues/209)

**Comment by Jansalvador1445** [comment]
Nice! Thanks sir for this one! merging this and adding you as @all-contributors please add @roycechua23  for content.


Congrats sir! keep it up! :D

**Comment by roycechua23** [comment]
Thanks sir @Jansalvador1445 😄 I'm looking forward to learn more about Flutter and contribute here as well.

**Pull request merged**
