### PR TITLE
Add "Ray Anthony M. Solis" details

### PR DESCRIPTION
**Pull request by ryansolis**
#30DaysofFlutter!

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Hi @ryansolis! Please rebase due to `conflicts`

**Comment by Jansalvador1445** [comment]
Has `conflicts` please rebase.

**Comment by Jansalvador1445** [comment]
Still has `Conflict`

**Comment by joshuadeguzman** [comment]
@all-contributors please add @ryansolis for content

**Pull request merged**
