### PR TITLE
Added Raine Holgado to devs.json

### LINKED ISSUE #145: Add Raine to devs.json

### PR DESCRIPTION
**Pull request by RaineHolgado**
Closed #145

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Kindly, put your name at the last part, thanks! and don't forget to pull. Thanks! @RaineHolgado

**Comment by RaineHolgado** [comment]
@Jansalvador1445 Done po..nalagay na sa last part

**Comment by Jansalvador1445** [comment]
Has a conflict, please rebase.

**Comment by RaineHolgado** [comment]
@Jansalvador1445 na rebase ko na po..Paki check ulit if okay naba..Slmat

**Comment by Jansalvador1445** [comment]
This is Good, Closing #145 , adding you as a contributor. 

@all-contributors please add @RaineHolgado for content

**Pull request merged**
