### PR TITLE
Issue #110 Added Wesley to contributor

### PR DESCRIPTION
**Pull request by Eastly1997**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Hi @Eastly1997 ! Conflict, can you rebase this one

**Comment by Eastly1997** [comment]
Hello I think I solve the conflict?

**Comment by Jansalvador1445** [comment]
This is good! Ready to merge but is there created issue here? @Eastly1997

**Comment by Eastly1997** [comment]
Hello here is the issue that I opened.
https://github.com/flutterph/devs/issues/110

**Comment by Jansalvador1445** [comment]
Merging this one and closing #110.  

@all-contributors please add @Eastly1997 for content

Thanks @Eastly1997 ! Congrats! You did a great job! :D

**Pull request merged**
