### PR TITLE
Add "Jan Tagadiad" details

### PR DESCRIPTION
**Pull request by 0wzZZzz6**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Conflict, please rebase this to master

**Comment by 0wzZZzz6** [comment]
@Jansalvador1445 I think its okay now sir

**Comment by Jansalvador1445** [comment]
Conflict, can you rebase it.

**Comment by Jansalvador1445** [comment]
This is now good for me, ready for merging. Just a quick question, did you filed an issue for this? if yes, kindly, comment the link here. thanks! :D

**Comment by 0wzZZzz6** [comment]
https://github.com/flutterph/devs/issues/108 here's the link sir.

**Comment by Jansalvador1445** [comment]
Great Job, @0wzZZzz6 ! Keep it up! 

Merging this now, closing the ticket, and then add you as a contributor. @all-contributors please add @0wzZZzz6 for content

**Comment by Jansalvador1445** [comment]
@all-contributors please add @0wzZZzz6 for content

**Pull request merged**
