### PR TITLE
Added loading indicator before loading DevsList

### PR DESCRIPTION
**Pull request by campanagerald**
Hi @Jansalvador1445, adding loading indicator before loading DevsList. 

[https://i.imgur.com/UHg4uVG.gif](https://i.imgur.com/UHg4uVG.gif)

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has `Conflict`, please rebase.

**Comment by joshuadeguzman** [comment]
Hello @campanagerald 

Please address the rebase conflict :D

If possible, I recommend adding a screenshot for feature and design related changes. cc: @Jansalvador1445 

Thanks for your PR!

**Comment by campanagerald** [comment]
HI @joshuadeguzman, i am having a hard time switching from stable to beta branch. After flutter upgrade, I am always stuck in Building flutter tool stage. so I decided to stick in the stable branch. being said that, i would like to close this issue and give this task to other devs :)

**Comment by campanagerald** [comment]
> HI @joshuadeguzman @Jansalvador1445 , i am having a hard time switching from stable to beta branch. After flutter upgrade, I am always stuck in Building flutter tool stage. so I decided to stick in the stable branch. being said that, i would like to close this issue and give this task to other devs :)

Hi @Jansalvador1445 @joshuadeguzman disregard this, I was able to fix the issue. I am working on this now. thanks :D

**Comment by campanagerald** [comment]
@Jansalvador1445 boss pa review po. :D Maraming salamat!

**Review by Jansalvador1445 — APPROVED** [review]
This is `Approved` on my side. @joshuadeguzman  could you also review this one.

**Pull request merged**
