### PR TITLE
add Medwin Correo to dev

### PR DESCRIPTION
**Pull request by MedwinCorreo**

### CODE REVIEW

**Review by joshuadeguzman — APPROVED** [review]

**Comment by joshuadeguzman** [comment]
Congrats @MedwinCorreo!  🎉

**Comment by joshuadeguzman** [comment]
@all-contributors add

**Comment by joshuadeguzman** [comment]
@all-contributors please add @MedwinCorreo

**Comment by joshuadeguzman** [comment]
@all-contributors please add @MedwinCorreo for content

**Comment by MedwinCorreo** [comment]
thanks for the approval sir josh D. 

kasama ka po pala sa Will of D .,

**Pull request merged**
