### PR TITLE
52/ronealdenila

### LINKED ISSUE #52: Add "Roneal Denila" to Dev Board

### PR DESCRIPTION
**Pull request by ronealdenila**
- Closes #52

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has a `conflict`. Maybe, you could `pull` the branch and then add the needed details! If there's any concern/problem. Don't hesitate to ask question! :D

**Comment by ronealdenila** [comment]
Im very sorry 😔

**Comment by Jansalvador1445** [comment]
Sure thing @ronealdenila ! It's a normal thing! It happens to anyone. Feel free to reach out to us ha? 🗡️  Keep grinding!

**Comment by ronealdenila** [comment]
Will do, thanks!

**Comment by joshuadeguzman** [comment]
@all-contributors add @ronealdenila  for content

**Pull request merged**
