### PR TITLE
Add Jan Dranreb Balangue dev list

### PR DESCRIPTION
**Pull request by shadowprend**
#216 add Jan Dranreb Balangue Dev List

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has a conflict, please rebase.

**Comment by Jansalvador1445** [comment]
Has no conflict but i think you need to `pull` the latest changes on master and then rebase. The reason why if i merge this now, `username` will be removed. So, please `pull`, `rebase`, `add` and then `push`. Thanks! :D

**Comment by Jansalvador1445** [comment]
and you didn't add yourself on the JSON fil. hehe

**Comment by shadowprend** [comment]
i open new pull request thanks

**Comment by Jansalvador1445** [comment]
Closing this PR to prevent doubled PR. Next time, if you want to open new PR, please don't forget to cancel the other branch thanks!

**Pull request closed without merging**
