### PR TITLE
Add Jan Dranreb details

### PR DESCRIPTION
**Pull request by shadowprend**

### CODE REVIEW

**Comment by shadowprend** [comment]
#220 Add Jan Dranreb details

**Comment by Jansalvador1445** [comment]
Has a `conflict` please rebase.

**Comment by shadowprend** [comment]
nanaman hahaha ako pa naman una naka lagay ng name hahaha gege

**Comment by shadowprend** [comment]
done rebase

**Comment by Jansalvador1445** [comment]
This is good, merging this one. Congrats :)

@all-contributors please add  @shadowprend  for content

**Comment by Jansalvador1445** [comment]
Closing this one.

**Pull request merged**
