### PR TITLE
Add John Lester D. Necesito details

### PR DESCRIPTION
**Pull request by Zacharias02**

### CODE REVIEW

**Comment by Jansalvador1445** [comment]
Has Conflict, please rebase. Thanks!

**Comment by joshuadeguzman** [comment]
Hi @Zacharias02,

I recommend having the following:
- Add "Closes #<issue-number" in your pull request details

Thanks for your PR!

**Comment by Jansalvador1445** [comment]
Still has `Conflict`

**Review by joshuadeguzman — APPROVED** [review]

**Comment by joshuadeguzman** [comment]
@all-contributors please add @Zacharias02  for content

**Pull request merged**
